### ISSUE TITLE
Regarding data insertion to MongoDB

### ISSUE THREAD

**Issue by arghyakusumdas** [Angel0117/Application_in_Information_Systems_Project#1]
If you cannot read csv file from HTML/Javascript add a form to your project to insert the records manually to MongoDB.
Then, insert all the records to MongoDB from back end.
This way you can recover some points

**Comment by CMelhaire** [comment]
I managed to get the files to load manually by firing a command on the terminal to import the entire .csv file into the database.  I was also able to copy the data, perform search and sort on the data, and examine the collection to find all 318,000+ records so that we know they are present inside the database.
